### ISSUE TITLE
Internal space line is trimmed in converted plaintext

### ISSUE THREAD

**Issue by Goooler** [commonmark/commonmark-java#334] opened 2024-08-06 10:39 UTC
Convert markdown to plaintext using:

```kt
private fun convertMarkdownToPlaintext(markdown: String): String {
    val parser = Parser.builder().build()
    val document = parser.parse(markdown)
    val renderer = TextContentRenderer.builder().build()
    return renderer.render(document)
}
```

Example:

```markdown
this
is 

**note**
```

Expected plaintext:

```
this
is

note
```

Actual plaintext:

```
this
is
note
```

(Also see what the reference implementation does: https://spec.commonmark.org/dingus/)

**Comment by boyshell** [comment] 2024-08-06 10:40
您好！邮件已收到。

**Comment by robinst** [comment] 2024-09-12 14:00
The plain text renderer is not really well-defined. But this is something we might change (CC @JinneeJ). Out of interest, what are you using it for?

**Comment by Goooler** [comment] 2024-09-13 00:09
I use this to convert markdown from a rich text editor on Android.

**Comment by robinst** [comment] 2024-09-18 08:55
Ah this came up in https://github.com/commonmark/commonmark-java/issues/264 as well. Happy to accept a patch for this as an option on `TextContentRenderer.Builder`.

**Comment by robinst** [comment] 2024-09-24 08:53
Closing as a duplicate of #264

**Closed by robinst** 2024-09-24 08:53 UTC
Labels: bug, help wanted
