### ISSUE TITLE
Erratic parsing

### ISSUE THREAD

**Issue by hrobache** [commonmark/commonmark-java#202] opened 2021-02-25 17:55 UTC
Steps to reproduce the problem (provide example Markdown if applicable):

```
this is a **test-**a
```

Expected behavior: The result should be having "test-" in bold

```
expected HTML: <p>this is a <strong>test-</strong>a</p>

```

Actual behavior: The parsing fails and does not recognize "**"

```
actual HTML:  <p>this is a **test-**a</p>
```

(Also see what the reference implementation does: https://spec.commonmark.org/dingus/): same (bad) result

**Comment by robinst** [comment] 2021-02-26 05:24
Yep, this is not a bug, it's according to the commonmark specification. I think the closest example from the spec is this: https://spec.commonmark.org/0.29/#example-379

We will not change the implementation to deviate from the spec, closing this.

**Closed by robinst** 2021-02-26 05:24 UTC
Labels: bug
